[[Zellij]]
arch = "aarch64"
git-tree-sha1 = "6eea52fc487e102d9abc2cb9b293ec9c88863748"
os = "macos"

    [[Zellij.download]]
    sha256 = "f80f73e0ad8dab31127012239b0445a650404d84009b29338e46ee4c473c91c6"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.25.0+0/Zellij.v0.25.0.aarch64-apple-darwin.tar.gz"
[[Zellij]]
arch = "aarch64"
git-tree-sha1 = "df2b0f09d9b9216b7a425e5b096afcc33983c36f"
libc = "glibc"
os = "linux"

    [[Zellij.download]]
    sha256 = "6f4eb3832ab26fe9dcad73a89470e085453f2639cb62579f227e40419171250f"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.25.0+0/Zellij.v0.25.0.aarch64-linux-gnu.tar.gz"
[[Zellij]]
arch = "aarch64"
git-tree-sha1 = "07f9fdb204c1eab27be51a1d621212e3a0b39a21"
libc = "musl"
os = "linux"

    [[Zellij.download]]
    sha256 = "3a4414bf032b59cead7747d8deb49884de75d6b34f3555f8cfcfebe8974ae54c"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.25.0+0/Zellij.v0.25.0.aarch64-linux-musl.tar.gz"
[[Zellij]]
arch = "i686"
git-tree-sha1 = "4ea509f5a9804f82e9160d2c1632c8c03b82533a"
libc = "glibc"
os = "linux"

    [[Zellij.download]]
    sha256 = "4463e937e0774fd2c82c2d29c32b1f08ad5b8d6775359a449a013b4dd18066d2"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.25.0+0/Zellij.v0.25.0.i686-linux-gnu.tar.gz"
[[Zellij]]
arch = "x86_64"
git-tree-sha1 = "a7f32f8871514ccc8f7d8df41c977cc03dc40e9c"
os = "macos"

    [[Zellij.download]]
    sha256 = "2416918732cf932fa06664d87f48242d68228ba11d5ec0daf12949a392ae240e"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.25.0+0/Zellij.v0.25.0.x86_64-apple-darwin.tar.gz"
[[Zellij]]
arch = "x86_64"
git-tree-sha1 = "8208004149aafaef2e701815908d19b6bb0ef1d6"
libc = "glibc"
os = "linux"

    [[Zellij.download]]
    sha256 = "08ad5a7703b5192901adc3567f35d094ba0b9811bc44ef1a2e5b56406b263631"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.25.0+0/Zellij.v0.25.0.x86_64-linux-gnu.tar.gz"
[[Zellij]]
arch = "x86_64"
git-tree-sha1 = "a671a2b4c8002d5cb0ef84a4c4e7597f8fc8092f"
libc = "musl"
os = "linux"

    [[Zellij.download]]
    sha256 = "b1c580dc6234516eba56f1586c55090547d1b849b3852aad6f3fca7f7968d424"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.25.0+0/Zellij.v0.25.0.x86_64-linux-musl.tar.gz"
