[[Zellij]]
arch = "aarch64"
git-tree-sha1 = "e3da2fec413aadc1d6cd88a4897b497de13a1a1a"
os = "macos"

    [[Zellij.download]]
    sha256 = "32cb5cd66592f3625283aeb87b23478fa062e06a018344fbafa2569b37148733"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.27.0+0/Zellij.v0.27.0.aarch64-apple-darwin.tar.gz"
[[Zellij]]
arch = "aarch64"
git-tree-sha1 = "e20333afb0b99a403ca686d73748f2f9c4bab6bf"
libc = "glibc"
os = "linux"

    [[Zellij.download]]
    sha256 = "58e1a0056db65d150d40e1f214130bde906c9a22a701c96d495c41203b3abf92"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.27.0+0/Zellij.v0.27.0.aarch64-linux-gnu.tar.gz"
[[Zellij]]
arch = "aarch64"
git-tree-sha1 = "920081fcb7010a303b26bcfc82ca828c653208cb"
libc = "musl"
os = "linux"

    [[Zellij.download]]
    sha256 = "8d687da322d683294a6cb28decc067fa0b1528765c33edcbb1212e842a27954d"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.27.0+0/Zellij.v0.27.0.aarch64-linux-musl.tar.gz"
[[Zellij]]
arch = "i686"
git-tree-sha1 = "555908b7c21de283fc64627daef95df0e1841a66"
libc = "glibc"
os = "linux"

    [[Zellij.download]]
    sha256 = "aa90587d5ee7222d53093b25a1a1727c40dbca24fadb113029f1a79e3b127f00"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.27.0+0/Zellij.v0.27.0.i686-linux-gnu.tar.gz"
[[Zellij]]
arch = "x86_64"
git-tree-sha1 = "5cef476d2a1a295392b21f97e370de502ea47437"
os = "macos"

    [[Zellij.download]]
    sha256 = "16f732ec6f088a035da48c3d6abeeddc769a2a638266724987c7eb117d38bde0"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.27.0+0/Zellij.v0.27.0.x86_64-apple-darwin.tar.gz"
[[Zellij]]
arch = "x86_64"
git-tree-sha1 = "378b86d1061401dd6cb7472320f31420a7a87f71"
libc = "glibc"
os = "linux"

    [[Zellij.download]]
    sha256 = "d19718553536447fed895eed0ddb528f2552f23c55c351b1de62feffbfe52aa4"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.27.0+0/Zellij.v0.27.0.x86_64-linux-gnu.tar.gz"
[[Zellij]]
arch = "x86_64"
git-tree-sha1 = "2c20ffd735f200681d50a6a20cd6075352aa4945"
libc = "musl"
os = "linux"

    [[Zellij.download]]
    sha256 = "376fe3bab44f1976516fa520cd8ff792afd0da08eb5ad69e09ec89db92083556"
    url = "https://github.com/JuliaBinaryWrappers/Zellij_jll.jl/releases/download/Zellij-v0.27.0+0/Zellij.v0.27.0.x86_64-linux-musl.tar.gz"
